name: CI Pipeline
run-name: ${{ github.actor }} triggered CI pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: "db"
          POSTGRES_PASSWORD: "changethis123"
          POSTGRES_DB: "db"
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Run app
        run: |
          poetry run bash ./prestart.sh
          poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000

      - name: Test code
        run: |
          # Run pytest tests
          pytest .

